import streamlit as st
import sqlite3
import pandas as pd
from datetime import datetime
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
import io

# ================= PAGE CONFIG =================
st.set_page_config(page_title="Hospital Management System", page_icon="🏥", layout="wide")

# ================= CUSTOM CSS =================
st.markdown("""
<style>
    .main-header { font-size: 48px; font-weight: bold; color: #1E88E5; text-align: center; margin-bottom: 30px; }
    .section-header { font-size: 28px; color: #1565c0; margin-top: 40px; }
    .form-box { background-color: #f8f9fa; padding: 25px; border-radius: 15px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); margin-bottom: 30px; }
    .stButton>button { background-color: #4CAF50; color: white; font-weight: bold; border-radius: 8px; padding: 12px; }
    .delete-btn > button { background-color: #f44336; }
    .pdf-btn > button { background-color: #1976d2; color: white; }
    .search-box { background-color: #f0f8ff; padding: 20px; border-radius: 12px; border-left: 6px solid #2196F3; margin-bottom: 30px; }
</style>
""", unsafe_allow_html=True)

# ================= DATABASE =================
DB = "hospital.db"

def init_db():
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    c.executescript('''
        CREATE TABLE IF NOT EXISTS Patients (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            cnic TEXT UNIQUE,
            phone TEXT
        );
        CREATE TABLE IF NOT EXISTS Doctors (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            cnic TEXT UNIQUE,
            department TEXT
        );
        CREATE TABLE IF NOT EXISTS Appointments (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            patient TEXT,
            patient_cnic TEXT,
            doctor TEXT,
            doctor_cnic TEXT,
            date TEXT,
            time TEXT,
            status TEXT
        );
        CREATE TABLE IF NOT EXISTS MedicalRecords (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            patient TEXT,
            patient_cnic TEXT,
            doctor TEXT,
            diagnosis TEXT,
            treatment TEXT,
            prescription TEXT,
            date TEXT
        );
        CREATE TABLE IF NOT EXISTS Billings (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            patient TEXT,
            patient_cnic TEXT,
            amount REAL,
            details TEXT,
            status TEXT
        );
    ''')
    conn.commit()
    conn.close()

init_db()

# ================= HELPERS =================
def query(sql, params=()):
    conn = sqlite3.connect(DB)
    df = pd.read_sql_query(sql, conn, params=params)
    conn.close()
    return df

def execute(sql, params=()):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    c.execute(sql, params)
    conn.commit()
    conn.close()

# ================= GENERIC PDF GENERATOR =================
def generate_pdf_report(title, headers, data, filename_prefix):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # Title
    story.append(Paragraph(title, styles['Title']))
    story.append(Spacer(1, 20))

    # Generated date
    story.append(Paragraph(f"Generated on: {datetime.now().strftime('%B %d, %Y')}", styles['Normal']))
    story.append(Spacer(1, 20))

    # Table
    table_data = [headers] + data
    table = Table(table_data)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E88E5')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f0f8ff')),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
    ]))
    story.append(table)

    story.append(Spacer(1, 40))
    story.append(Paragraph("Generated by Hospital Management System", styles['Italic']))

    doc.build(story)
    buffer.seek(0)
    return buffer

# ================= SIDEBAR =================
st.sidebar.markdown("<h2 style='color:#1E88E5;'>🏥 Hospital System</h2>", unsafe_allow_html=True)
menu = st.sidebar.radio("Navigate", ["Dashboard", "Patients", "Doctors", "Appointments", "Medical Records", "Billings"])

# ================= DASHBOARD =================
if menu == "Dashboard":
    st.markdown('<div class="main-header">🏥 Hospital Dashboard</div>', unsafe_allow_html=True)
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Patients", len(query("SELECT * FROM Patients")))
    col2.metric("Doctors", len(query("SELECT * FROM Doctors")))
    col3.metric("Appointments", len(query("SELECT * FROM Appointments")))
    col4.metric("Bills", len(query("SELECT * FROM Billings")))
    st.success("Dashboard loaded successfully!")

# ================= PATIENTS =================
elif menu == "Patients":
    st.markdown('<div class="main-header">👥 Patients Management</div>', unsafe_allow_html=True)
    patients_df = query("SELECT * FROM Patients")
    st.subheader("All Patients")
    st.dataframe(patients_df, use_container_width=True)

    # PDF Export
    if not patients_df.empty:
        data = patients_df[["id", "name", "cnic", "phone"]].values.tolist()
        pdf_buffer = generate_pdf_report("Patients List Report", ["ID", "Name", "CNIC", "Phone"], data, "Patients")
        st.markdown('<div class="pdf-btn">', unsafe_allow_html=True)
        st.download_button(
            label="📄 Download All Patients as PDF",
            data=pdf_buffer,
            file_name=f"Patients_Report_{datetime.now().strftime('%Y%m%d')}.pdf",
            mime="application/pdf"
        )
        st.markdown('</div>', unsafe_allow_html=True)

    # CRUD forms (add your existing add/update/delete code here)

# ================= DOCTORS =================
elif menu == "Doctors":
    st.markdown('<div class="main-header">👨‍⚕️ Doctors Management</div>', unsafe_allow_html=True)
    doctors_df = query("SELECT * FROM Doctors")
    st.subheader("All Doctors")
    st.dataframe(doctors_df, use_container_width=True)

    # PDF Export
    if not doctors_df.empty:
        data = doctors_df[["id", "name", "cnic", "department"]].values.tolist()
        pdf_buffer = generate_pdf_report("Doctors List Report", ["ID", "Name", "CNIC", "Department"], data, "Doctors")
        st.markdown('<div class="pdf-btn">', unsafe_allow_html=True)
        st.download_button(
            label="📄 Download All Doctors as PDF",
            data=pdf_buffer,
            file_name=f"Doctors_Report_{datetime.now().strftime('%Y%m%d')}.pdf",
            mime="application/pdf"
        )
        st.markdown('</div>', unsafe_allow_html=True)

    # CRUD forms

# ================= APPOINTMENTS =================
elif menu == "Appointments":
    st.markdown('<div class="main-header">🗓️ Appointments Management</div>', unsafe_allow_html=True)
    appointments_df = query("SELECT * FROM Appointments")
    st.subheader("All Appointments")
    st.dataframe(appointments_df, use_container_width=True)

    # PDF Export
    if not appointments_df.empty:
        data = appointments_df[["id", "patient", "doctor", "date", "time", "status"]].values.tolist()
        pdf_buffer = generate_pdf_report("Appointments List Report", ["ID", "Patient", "Doctor", "Date", "Time", "Status"], data, "Appointments")
        st.markdown('<div class="pdf-btn">', unsafe_allow_html=True)
        st.download_button(
            label="📄 Download All Appointments as PDF",
            data=pdf_buffer,
            file_name=f"Appointments_Report_{datetime.now().strftime('%Y%m%d')}.pdf",
            mime="application/pdf"
        )
        st.markdown('</div>', unsafe_allow_html=True)

    # CRUD forms

# ================= MEDICAL RECORDS =================
elif menu == "Medical Records":
    st.markdown('<div class="main-header">📋 Medical Records</div>', unsafe_allow_html=True)

    # Search for patient report
    st.markdown('<div class="search-box">', unsafe_allow_html=True)
    st.subheader("🔍 Search Patient for Medical Report")
    search_cnic = st.text_input("Enter Patient CNIC")
    search_btn = st.button("Search Records", type="primary")
    st.markdown('</div>', unsafe_allow_html=True)

    records_df = pd.DataFrame()
    patient_name = "Unknown"

    if search_btn and search_cnic:
        records_df = query("SELECT * FROM MedicalRecords WHERE patient_cnic = ? ORDER BY date DESC", (search_cnic,))
        if not records_df.empty:
            patient_name = records_df.iloc[0]["patient"]
            st.success(f"Found {len(records_df)} record(s) for {patient_name}")

    if not records_df.empty:
        st.subheader(f"Medical History - {patient_name}")
        st.dataframe(records_df, use_container_width=True)

        # Specific Patient Medical Report PDF
        data = records_df[["date", "doctor", "diagnosis", "treatment", "prescription"]].values.tolist()
        pdf_buffer = generate_pdf_report(f"Medical Report - {patient_name}", ["Date", "Doctor", "Diagnosis", "Treatment", "Prescription"], data, "Medical")
        st.markdown('<div class="pdf-btn">', unsafe_allow_html=True)
        st.download_button(
            label="📄 Download Patient Medical Report as PDF",
            data=pdf_buffer,
            file_name=f"Medical_Report_{patient_name.replace(' ', '_')}_{search_cnic}.pdf",
            mime="application/pdf"
        )
        st.markdown('</div>', unsafe_allow_html=True)

    # All Medical Records PDF
    all_records = query("SELECT * FROM MedicalRecords")
    if not all_records.empty:
        all_data = all_records[["patient", "patient_cnic", "date", "doctor", "diagnosis"]].values.tolist()
        all_pdf = generate_pdf_report("All Medical Records Report", ["Patient", "CNIC", "Date", "Doctor", "Diagnosis"], all_data, "AllMedical")
        st.download_button(
            label="📄 Download All Medical Records as PDF",
            data=all_pdf,
            file_name=f"All_Medical_Records_{datetime.now().strftime('%Y%m%d')}.pdf",
            mime="application/pdf"
        )

    # CRUD forms

# ================= BILLINGS =================
elif menu == "Billings":
    st.markdown('<div class="main-header">💰 Billing Management</div>', unsafe_allow_html=True)
    bills_df = query("SELECT * FROM Billings")
    st.subheader("All Bills")
    st.dataframe(bills_df, use_container_width=True)

    # PDF Export
    if not bills_df.empty:
        data = bills_df[["id", "patient", "patient_cnic", "amount", "status"]].values.tolist()
        pdf_buffer = generate_pdf_report("Billing Report", ["Bill ID", "Patient", "CNIC", "Amount", "Status"], data, "Billing")
        st.markdown('<div class="pdf-btn">', unsafe_allow_html=True)
        st.download_button(
            label="📄 Download All Bills as PDF",
            data=pdf_buffer,
            file_name=f"Billing_Report_{datetime.now().strftime('%Y%m%d')}.pdf",
            mime="application/pdf"
        )
        st.markdown('</div>', unsafe_allow_html=True)

    # CRUD forms

# ================= FOOTER =================
st.markdown("---")
st.markdown("<center>© 2025 Hospital Management System • Built with ❤️ using Streamlit</center>", unsafe_allow_html=True)
